let add = function(a, b){
    let result = a + b
    return result
}

console.log(add(5,4))
//console.log(result)   // Error as it's outside the scope